env:
  browser: true
  es2021: true
  node: true
extends:
  - eslint:recommended
  - plugin:react/recommended
  - plugin:@typescript-eslint/recommended
overrides: []
parser: "@typescript-eslint/parser"
parserOptions:
  ecmaVersion: latest
  sourceType: module
plugins:
  - react
  - "@typescript-eslint"
settings:
  react:
    version: "detect"
rules:
  {
    "no-unused-vars": "off",
    "comma-dangle": "off",
    "no-restricted-imports": "off",
    "@typescript-eslint/no-unused-vars": "error",
    "@typescript-eslint/comma-dangle": "error",
    "@typescript-eslint/no-restricted-imports": "warn",
    "@typescript-eslint/quotes": ["error", "double"],
  }
